### ISSUE TITLE
Modal feedback links are unreadable

### ISSUE THREAD

**Issue by VitorLuizC** [AshPowell/monokai-one-dark-vivid#1]
Change Modal feedback links to a color with more contrast.

<img width="518" alt="captura de tela 2017-08-27 as 15 54 44" src="https://user-images.githubusercontent.com/9027363/29753100-90e9e75c-8b40-11e7-8238-f30377221da2.png">

**Comment by AshPowell** [comment]
I'll look into it thanks for reporting - Any idea how I can open one of these modals to reproduce?

**Comment by AshPowell** [comment]
Thanks for reporting - will fix soon

**Comment by AshPowell** [comment]
Fixed  - 0.10.0

**Comment by AshPowell** [comment]
Although this is fixed - other buttons contrast is now not very good..

The problem is that the links on the 'other ways to contact us' use the buttons background colour, not foreground...

Will have to adjust other buttons foreground colour to address this
